############ RUN THIS ON EMPTY DB TO CREATE NEEDED DB TABLES ##########

CREATE TABLE `duomenys` (
	`D_ID` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
	`D_DATE_CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`D_ActualDate` DATETIME NULL DEFAULT NULL,
	`D_Temperature_1` FLOAT NULL DEFAULT NULL,
	`D_Humidity_1` FLOAT NULL DEFAULT NULL,
	`D_Temperature_2` FLOAT NULL DEFAULT NULL,
	`D_Humidity_2` FLOAT NULL DEFAULT NULL,
	`D_Temperature_3` FLOAT NULL DEFAULT NULL,
	`D_Pressure` FLOAT NULL DEFAULT NULL,
	`D_Temperature_4` FLOAT NULL DEFAULT NULL,
	`D_Info` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf16_lithuanian_ci',
	`D_Comments` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf16_lithuanian_ci',
	PRIMARY KEY (`D_ID`),
	INDEX `D_ActualDate` (`D_ActualDate`),
	INDEX `D_ID` (`D_ID`)
)
COLLATE='utf16_lithuanian_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `duomenys_minutiniai` (
	`DM_ID` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
	`DM_DATE_CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DM_ActualDate` DATETIME NULL DEFAULT NULL,
	`DM_Temperature_1` FLOAT NULL DEFAULT NULL,
	`DM_Humidity_1` FLOAT NULL DEFAULT NULL,
	`DM_Temperature_2` FLOAT NULL DEFAULT NULL,
	`DM_Humidity_2` FLOAT NULL DEFAULT NULL,
	`DM_Temperature_3` FLOAT NULL DEFAULT NULL,
	`DM_Pressure` FLOAT NULL DEFAULT NULL,
	`DM_Temperature_4` FLOAT NULL DEFAULT NULL,
	`DM_Info` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf16_lithuanian_ci',
	`DM_Comments` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf16_lithuanian_ci',
	PRIMARY KEY (`DM_ID`),
	INDEX `DM_ID` (`DM_ID`),
	INDEX `DM_ActualDate` (`DM_ActualDate`)
)
COLLATE='utf16_lithuanian_ci'
ENGINE=InnoDB
AUTO_INCREMENT=155383
;


####### FUNCTION USED TO CLEAN OLD DATA FROM warehouse.duomenys_minutiniai 

CREATE DEFINER=`aviete`@`localhost` EVENT `DM CleanUp`
	ON SCHEDULE
		EVERY 1 HOUR STARTS '2015-02-12 13:37:30'
	ON COMPLETION PRESERVE
	ENABLE
	COMMENT 'Task for deleting old data'
	DO BEGIN
delete
from warehouse.duomenys_minutiniai 
where duomenys_minutiniai.DM_ActualDate < DATE_SUB(NOW(), INTERVAL 30 MINUTE);
END


